source 'https://github.com/CocoaPods/Specs.git'

workspace 'XYZAdDemo.xcworkspace'

platform :ios, '9.0'

use_frameworks!
use_modular_headers!




targetsArray = ['XYZAdDemo']

targetsArray.each do |t|
    target t do
        pod 'Masonry'
        pod 'YYWebImage'
        
        pod 'XYZAd', '1.4.3'
        #集成禾赞
        pod 'XYZAd/HZSDK', '1.4.3'
        #集成穿山甲
        pod 'XYZAd/JRTTSDK', '1.4.3'
        #集成百度
        pod 'XYZAd/BDSDK', '1.4.3'
        #集成广点通
        pod 'XYZAd/GDTSDK', '1.4.3'
        #集成MTG
        pod 'XYZAd/MTGSDK', '1.4.3'
        #集成SigmobAd
        pod 'XYZAd/SIGMOBSDK', '1.4.3'
        #集成快手
        pod 'XYZAd/KSMOBSDK', '1.4.3'
        #集成聚合
        pod 'XYZAd/JHSDK', '1.4.3'
        #集成游可盈
        pod 'XYZAd/YouKeYingDK', '1.4.3'

    end
end


# 这个是cocoapods的一些配置,官网并没有太详细的说明,一般采取默认就好了,也就是不写.
#post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     puts target.name
#   end
#end
